### PR TITLE
Changed trillion to billion and edge case is taken care

### LINKED ISSUE #118: [BUG] Incorrect unit in `RoundValues()`
**Describe the bug**
In the `utils` package, the `RoundValues()` function has a small error where the switch case classifies units as `per thousand`, `per million` and **`per trillion`**. Additionally, no default case is set, which could lead to the function returning empty values.

**To Reproduce**
Unsure how to reproduce.

**Expected behaviour**
The third unit must be `per billion` and not `per trillion`

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Go Version 1.16

### PR DESCRIPTION
**Pull request by mihirkestur**
For the edge case (n >= T), numbers will be represented in terms of "gB" units. i.e. All numbers greater than or equal to 10^9 will be represented in terms of gigabytes (billion bytes). This resolves the edge case, if numbers were greater than 10^12, empty values would be returned.

Fixes #118 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X] I have read the [contribution guidelines](https://github.com/pesos/grofer/blob/master/CONTRIBUTING.md) and followed it as far as possible. 
- [ ] I have performed a self-review of my own code (if applicable)
- [ ] I have commented my code, particularly in hard-to-understand areas (if applicable)
- [ ] I have run `go fmt` on my code ([reference](https://blog.golang.org/gofmt))
- [ ] I have made corresponding changes to the documentation (if applicable)
- [X] My changes generate no new warnings 
- [ ] Any dependent and pending changes have been merged and published

### CODE REVIEW

File: src/utils/dataFormat.go [hunk 1]
```diff
@@ -25,7 +25,6 @@ var (
 	K = math.Pow(10, 3)
 	M = math.Pow(10, 6)
 	G = math.Pow(10, 9)
-	T = math.Pow(10, 12)
 )
```
Comment (Gituser143) [inline src/utils/dataFormat.go:28]: @mihirkestur Although this makes sense, maybe it would be better to retain T (Trillion, Peta Bytes), maybe making Peta Bytes as the last case would be better. I know it's unlikely to have metrics in pB, but it is a possibility.

**Review by Gituser143 — CHANGES_REQUESTED** [review]

File: src/utils/dataFormat.go (hunk 1 above)
Comment (mihirkestur) [reply src/utils/dataFormat.go:28]: Alright sure!

**Review by Gituser143 — APPROVED** [review]
Looks good to me! I'll let the next reviewer merge this.
CC @MadhavJivrajani @Samyak2

**Review by MadhavJivrajani — APPROVED** [review]
Thanks for your contribution 🎉 ❤️
